name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ####################
  # Linux
  ####################

  Linux:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        config: [Debug, Release]
        include:
          - os: ubuntu-latest
            name: Linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 10

      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build
        run: cd build; make -j2

      - name: Tests
        if: matrix.config == 'Debug'
        run: cd build; ./mesh_generator


  ####################
  # MacOS
  ####################

  MacOS:
    name: ${{ matrix.name }}-${{ matrix.arc }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        arc: [x86]
        config: [Debug, Release]
        include:
          - os: macos-latest
            name: macOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 10

      - name: Configure x86
        if: matrix.arc == 'x86'
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Configure arm64
        if: matrix.arc == 'arm64'
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
            -DCMAKE_OSX_ARCHITECTURES=arm64

      - name: Build
        run: cd build; make -j2

      - name: Tests
        if: matrix.config == 'Debug'
        run: cd build; ./mesh_generator

  ####################
  # Windows
  ####################

  Windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 10

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure and Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          cmake -G Ninja ^
            -DCMAKE_BUILD_TYPE=${{ matrix.config }} ^
            -B build ^
            -S .
          cmake --build build -j1

      - name: Tests
        if: matrix.config == 'Debug'
        run: |
          cd build
          .\\mesh_generator.exe
